### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wolfiton** [tinfoil/wormwood#13]
I am currently learning absinthe using this book https://pragprog.com/book/wwgraphql/craft-graphql-apis-in-elixir-with-absinthe and was wondering if the @WormwoodTeam would be interested in helping me to convert the testing code from Exunit to Wormwood. 

I already wrote some of it and I am going to continue doing so as I progress through the book.

I only need assistance from time to time. Can you help me?

This way everybody wins:

- Wormwood project will get documentation and examples and a test against a robust application with a lot of use cases

- I get to learn Wormwood testing

Thanks

**Comment by QuinnWilton** [comment]
Since copyrights apply to the source code for the book, we don't actually have permission to make use of it for producing training materials and documentation: https://pragprog.com/titles/wwgraphql/source_code

If you run into bugs as you translate the examples for your own purposes, however, definitely feel free to open issues :)

**Comment by wolfiton** [comment]
Then can I write my blog app WolfCMS that will be under Apache 2.0 and test it with Wormwood.
Would that work?

**Comment by QuinnWilton** [comment]
I think that that would fall within the restrictions placed by the copyright notice, but I'm not a lawyer. 

All of this being said, I think it's probably for the best if we don't include those examples within the Wormwood project.

**Comment by wolfiton** [comment]
OK,

Thank you very much for the quick responses.
